services:
  mariadb:
    container_name: mariadb
    image: mariadb:10.11
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - DB:/var/lib/mysql
    networks:
      - inception
      
  wordpress:
    container_name: wordpress
    image: wordpress:fpm
    depends_on:
      - mariadb
    ports:
      - "9000:9000"
    env_file:
      - .env
    volumes:
      # Official image requires /var/www/html
      - wordpress:/var/www/html
    networks:
      - inception
      
  nginx:
    container_name: nginx
    image: nginx:latest
    depends_on:
      - wordpress
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
    networks:
      - inception
    volumes:
          # NGINX needs access to the exact same path to serve static files
          - wordpress:/var/www/html
          - ./requirements/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
          - /home/ubuntu/data/ssl:/etc/nginx/ssl:ro

volumes:
  DB:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ubuntu/data/mysql
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ubuntu/data/wordpress

networks:
  inception:
    driver: bridge