#!/bin/bash

echo "STARTING MARIADB INITIALIZATION"
service mariadb start
sleep 5
mariadb -u root << EOF
CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS '${MYSQL_USER}'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}';
CREATE USER IF NOT EXISTS '${MYSQL_USER}'@'localhost' IDENTIFIED BY '${MYSQL_PASSWORD}';
GRANT ALL PRIVILEGES ON *.* TO '${MYSQL_USER}'@'%';
GRANT ALL PRIVILEGES ON *.* TO '${MYSQL_USER}'@'localhost';
FLUSH PRIVILEGES;
EOF
echo "DATABASE INITIALIZATION COMPLETED :D"


mysqladmin -u root -p"${MYSQL_ROOT_PASSWORD}" shutdown
sleep 2
echo "STILL RUNIIIIIIIING"
exec mysqld_safe